"""Bridge to Codex's memory store.

Codex keeps distilled per-thread memories in ``$CODEX_HOME/memories_*.sqlite``
(``stage1_outputs``: one row per thread, with the raw memory and a summary), and
drives its own background work through a ``jobs`` table with ownership tokens
and leases.

**The direction is deliberately asymmetric, and it is not preference.**

* *Reading* is safe: the database is opened read-only and immutable, so nothing
  here can disturb Codex, whatever it is doing at the time.
* *Writing back into that database is not done at all.* It is another product's
  internal schema, versioned by its own ``_sqlx_migrations`` table and guarded by
  a lease protocol this process is not part of. Inserting rows would mean
  claiming a thread id we do not own and racing a worker that holds the lease —
  precisely the class of bug this repository exists to demonstrate. A migration
  on Codex's side could also drop whatever was written.

So the write-back surface is the one Codex actually reads as text: an
``AGENTS.md``-style markdown file, which you point at from your ``AGENTS.md``.
Claude Code's auto-memory is synced in both directions (see :mod:`claude_sync`)
because its store *is* a directory of markdown files with a documented shape —
writing there is writing the same kind of file a human would.
"""
from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

STAGE1_TABLE = "stage1_outputs"


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))


def memories_db(home: "str | Path | None" = None) -> Path | None:
    """The newest ``memories_*.sqlite``, since the suffix tracks their schema."""
    home = Path(home) if home is not None else codex_home()
    if not home.is_dir():
        return None
    candidates = sorted(home.glob("memories_*.sqlite"))
    return candidates[-1] if candidates else None


def read_memories(db_path: "str | Path | None" = None) -> list[dict[str, Any]]:
    """Every distilled memory Codex holds. Read-only; never mutates the file."""
    path = Path(db_path) if db_path is not None else memories_db()
    if path is None or not Path(path).is_file():
        return []
    # immutable=1 promises we will not write, and skips locking entirely, so a
    # running Codex is neither blocked nor disturbed.
    uri = f"file:{Path(path).as_posix()}?mode=ro&immutable=1"
    try:
        con = sqlite3.connect(uri, uri=True)
    except sqlite3.Error:
        return []
    try:
        con.row_factory = sqlite3.Row
        tables = {r[0] for r in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table'")}
        if STAGE1_TABLE not in tables:
            return []
        cols = {r["name"] for r in con.execute(f"PRAGMA table_info({STAGE1_TABLE})")}
        wanted = [c for c in ("thread_id", "raw_memory", "rollout_summary",
                              "rollout_slug", "generated_at", "usage_count")
                  if c in cols]
        rows = con.execute(
            f"SELECT {', '.join(wanted)} FROM {STAGE1_TABLE}").fetchall()
    except sqlite3.Error:
        return []
    finally:
        con.close()
    return [dict(r) for r in rows]


def sync(store, *, db_path: "str | Path | None" = None) -> dict[str, Any]:
    """Import Codex's memories into the store. Import only, by design."""
    rows = read_memories(db_path)
    known = {(o.get("meta") or {}).get("thread_id")
             for o in store.all() if (o.get("meta") or {}).get("origin") == "codex"}
    imported = 0
    for row in rows:
        thread_id = row.get("thread_id")
        if not thread_id or thread_id in known:
            continue
        question = (row.get("rollout_summary") or row.get("rollout_slug")
                    or f"codex thread {thread_id}")
        store.remember(
            str(question), str(row.get("raw_memory") or ""),
            meta={"origin": "codex", "thread_id": str(thread_id),
                  "rollout_slug": str(row.get("rollout_slug") or ""),
                  "usage_count": str(row.get("usage_count") or "")},
        )
        known.add(thread_id)
        imported += 1
    return {"db": str(db_path or memories_db() or ""),
            "rows": len(rows), "imported": imported}


def render_agents_memory(observations: list[dict[str, Any]], *, limit: int = 200) -> str:
    """Markdown for Codex to read as text, since its database is not ours to write."""
    lines = [
        "# Shared observations",
        "",
        "Generated by parallel-memory-mcp. Do not edit by hand — regenerate with",
        "`parallel-memory export-agents`.",
        "",
    ]
    for obs in observations[:limit]:
        meta = obs.get("meta") or {}
        origin = meta.get("origin") or "local"
        lines.append(f"## {obs['question']}")
        lines.append("")
        lines.append(f"- writer: `{obs['writer']}` · origin: `{origin}`"
                     + (f" · outcome: `{obs['outcome']}`" if obs.get("outcome") else ""))
        if obs.get("correction"):
            lines.append(f"- correction: {obs['correction']}")
        lines.append("")
        lines.append(obs["answer"].strip())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def export_agents_memory(observations: list[dict[str, Any]],
                         path: "str | Path") -> Path:
    """Write the markdown surface. Idempotent."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_agents_memory(observations)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
    return path
